"""done

Revision ID: 261df2d6fe18
Revises: ecd8e5aadaaa
Create Date: 2025-10-24 22:20:58.044952

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '261df2d6fe18'
down_revision = 'ecd8e5aadaaa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('telefone', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mensagem', sa.String(length=15), nullable=True))
        batch_op.add_column(sa.Column('respondido', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('telefone', schema=None) as batch_op:
        batch_op.drop_column('respondido')
        batch_op.drop_column('mensagem')

    # ### end Alembic commands ###
